### ISSUE TITLE
[US04] - Manter Grupo

### ISSUE THREAD

**Issue by MateusO97** [fga-eps-mds/2019.2-Amika-Backend#29]
**Sua funcionalidade requisitada é relacionada com um problema? Descreva, por favor.**

Eu, como usuário, desejo criar, visualizar, editar e deletar um grupo, para com isso organizar os estudantes durante o semestre.

**Descreva a solução que você gostaria**

Realizar um CRUD completo para Grupo, enviando seus dados via API para que possam ser consumidos no Front-End

**Descreva uma alternativa considerada**

- [ ] Criar Grupos aleatoriamente alocando os alunos cadastrados naquele semestre que ainda não tenham grupo
- [ ] Listar Grupos(Mostrando informações básicas, tais como membros, nome do grupo, etc.
- [ ] Editar Grupo(Editar nome do Grupo que vem por padrão numerados, Grupo 1, Grupo 2, etc)
- [ ] Deletar Grupo
- [ ] Adicionar/Remover um membro do grupo
- [ ] Ver detalhe do Grupo(Ver informações de somente um grupo)
- [ ] Testar todas as funcionalidades novas

**Informações adicionais**

**Checklist**  
- [x] A issue possui nome significativo.
- [x] A issue possui descrição significativa.
- [ ] A issue possui screenshots quando necessárias.
- [x] A issue possui labels.

## Critérios de aceitação

- [ ] Os commits seguem a [política de commits do repositório](https://fga-eps-mds.github.io/2019.2-Amika-Wiki/#/docs/projeto/planogerencia).
- [ ] As branches seguem a [política de branches do repositório](https://fga-eps-mds.github.io/2019.2-Amika-Wiki/#/docs/projeto/planogerencia).
- [ ] Não há erros de linter.
- [ ] A build está passando (travis, code climate).
- [ ] As funções são retornadas em rotas API para serem consumidas pelo Front-End

**Comment by cantuariavc** [comment]
Quantos alunos podem pertencer a um grupo?

**Comment by MateusO97** [comment]
> Quantos alunos podem pertencer a um grupo?

Não tem número exato, depende do semestre, mas normalmente são entre 10 e 15 pessoas
