### ISSUE TITLE
[US19] Manter Materiais

### ISSUE THREAD

**Issue by MateusO97** [fga-eps-mds/2019.2-Amika-Backend#49]
**Sua funcionalidade requisitada é relacionada com um problema? Descreva, por favor.**

Eu, como administrador, gostaria de enviar, alterar e remover materiais(anexos) para com isto divulgar as aulas e outros materiais utilizados na disciplina.

**Descreva a solução que você gostaria**

CRUD para administrador enviar, editar e remover materiais, e lista-los para usuário

**Descreva uma alternativa considerada**

**Informações adicionais**

**Checklist**  
- [x] A issue possui nome significativo.
- [x] A issue possui descrição significativa.
- [ ] A issue possui screenshots quando necessárias.
- [x] A issue possui labels.

**Critérios de aceitação**
- [ ] Os commits seguem a [política de commits do repositório](https://fga-eps-mds.github.io/2019.2-Amika-Wiki/#/docs/projeto/planogerencia).
- [ ] As branches seguem a [política de branches do repositório](https://fga-eps-mds.github.io/2019.2-Amika-Wiki/#/docs/projeto/planogerencia).
- [ ] Não há erros de linter.
- [ ] A build está passando (travis, code climate).
- [ ] Foram criadas rotas para serem consumidas no Frontend

**Comment by ithaloazevedo** [comment]
Mateus, o CRUD foi feito o pull request já foi enviado. :)

**Comment by MateusO97** [comment]
Ótimo, obrigado @ithaloazevedo :D assim que possível irei revisar
