### ISSUE TITLE
[US08] Visualizar Gráfico de Humor da Turma

### ISSUE THREAD

**Issue by MateusO97** [fga-eps-mds/2019.2-Amika-Backend#50]
**Sua funcionalidade requisitada é relacionada com um problema? Descreva, por favor.**

Eu, como administrador, gostaria de visualizar o gráfico de humor da turma para acompanhar o histórico de humor ao longo do tempo

**Descreva a solução que você gostaria**

Enviar os dados para que seja construido um gráfico no frontend

**Descreva uma alternativa considerada**

Olhar a necessidade se é possível realizar a US somente no Frontend, caso não seja, criar rotas no backend para passar os dados necessários via API.

**Informações adicionais**

**Checklist**  
- [x] A issue possui nome significativo.
- [x] A issue possui descrição significativa.
- [ ] A issue possui screenshots quando necessárias.
- [x] A issue possui labels.

**Critérios de aceitação**
- [ ] Os commits seguem a [política de commits do repositório](https://fga-eps-mds.github.io/2019.2-Amika-Wiki/#/docs/projeto/planogerencia).
- [ ] As branches seguem a [política de branches do repositório](https://fga-eps-mds.github.io/2019.2-Amika-Wiki/#/docs/projeto/planogerencia).
- [ ] Não há erros de linter.
- [ ] A build está passando (travis, code climate).
- [ ] Foram criadas rotas para serem consumidas no Frontend

**Comment by ArthurPaivaT** [comment]
Olá, @MateusO97 , é possível tanto usar uma API já existente no backend que envia todos os humores salvos em uma turma e tratar tudo no frontend quanto criar uma nova API para enviar apenas os humores da que tiver sido selecionada, ao meu ver é mais simples fazer da segunda forma já que na primeira também seria necessário enviar os dados de cada aluno pra fazer as comparações. O que acha melhor?

**Comment by MateusO97** [comment]
> Olá, @MateusO97 , é possível tanto usar uma API já existente no backend que envia todos os humores salvos em uma turma e tratar tudo no frontend quanto criar uma nova API para enviar apenas os humores da que tiver sido selecionada, ao meu ver é mais simples fazer da segunda forma já que na primeira também seria necessário enviar os dados de cada aluno pra fazer as comparações. O que acha melhor?

Acredito que para esta situação a segunda forma seria ideal, tanto por ser mais simples quanto no ponto de vista da usabilidade do usuário. Caso futuramente optem por utilizar esta primeira forma, avisem aqui na issue
