### ISSUE TITLE
Refatorar funcionalidade humor do dia

### ISSUE THREAD

**Issue by Matheus456** [fga-eps-mds/2019.2-Amika-Backend#59]
**Em que arquivo a refatoração é necessária?**
Atualmente o humor do dia não tem relacionamento com o usuário, ou seja, ele só é preenchido uma vez e vale para todos os usuários.

**Explique, de forma clara, o motivo pelo qual o arquivo deve ser refatorado:**
Cada usuário deve ter um humor do dia.

**Qual o estado atual do arquivo?**

**Qual o estado desejado do arquivo após a refatoração?**

**Checklist**  
- [x] A issue possui nome significativo.
- [x] A issue possui descrição significativa.
- [ ] A issue possui screenshots quando necessárias.
- [x] A issue possui labels.

**Comment by ithaloazevedo** [comment]
A refatoração já foi feita na branch #50

**Comment by Matheus456** [comment]
Issue foi resolvida em https://github.com/fga-eps-mds/2019.2-Amika-Backend/pull/78.
