### ISSUE TITLE
Retornar humor adicionado hoje

### ISSUE THREAD

**Issue by ArthurPaivaT** [fga-eps-mds/2019.2-Amika-Backend#79]
**Sua funcionalidade requisitada é relacionada com um problema? Descreva, por favor.**

O frontend precisa receber dados caso o usuário logado já tenha adicionado seu humor hoje

**Descreva a solução que você gostaria**

Verificar dentre os humores já adicionados se algum foi adicionado hoje pelo usuário atualmente logado e retornar esta verificação.

**Informações adicionais**

**Checklist**  
- [x] A issue possui nome significativo.
- [x] A issue possui descrição significativa.
- [ ] A issue possui screenshots quando necessárias.
- [x] A issue possui labels.

**Critérios de aceitação**
- [ ] Os commits seguem a [política de commits do repositório](https://fga-eps-mds.github.io/2019.2-Amika-Wiki/#/docs/projeto/planogerencia).
- [ ] As branches seguem a [política de branches do repositório](https://fga-eps-mds.github.io/2019.2-Amika-Wiki/#/docs/projeto/planogerencia).
- [ ] Não há erros de linter.
- [ ] A build está passando (travis, code climate).
- [ ] Foram criadas rotas para serem consumidas no Frontend

**Comment by Matheus456** [comment]
Esta issue foi resolvida em https://github.com/fga-eps-mds/2019.2-Amika-Backend/pull/78.
